In [371]:
import matplotlib.pyplot as plt
import numpy as np
import scipy
import scipy.linalg as linalg

In [372]:
xi = np.array ([2,5,7,10])
ni = np.array ([16,12,8,14])

In [373]:
x1 = xi*ni/(sum(ni)) #выборочное среднее
x = sum (x1)
x

5.76

След задача

In [374]:
xi = np.array ([0,1,2,3,4])
ni = np.array ([132,43,20,3,2])

In [375]:
x  = sum(xi*ni)/sum(ni) #выборочное среднее
x

0.5

след задача

In [376]:
xi = np.array ([37.5, 62.5, 87.5, 112.5, 137.5, 162.5, 187.5, 250, 350])
ni = np.array ([1, 3, 6, 7, 7, 5, 4, 8, 4])

In [377]:
xb = sum(xi*ni)/sum(ni) #выборочное среднее
mas = np.full(len(xi), xb.mean()) #создание массива с одинаковыми элементами (длина массива, его наполнение)
db = (1/sum(ni))*sum(ni*(xi - mas)**2) #дисперсия

след задача функция лапласса (сделать интеграл функции лапласса)

Задание 2. Построить линейную регрессию Х2 от Х1. Найти доверительные интервалы для параметров.

In [378]:
x1 = np.array ([0.73, 2.59, -2.66, -0.14, 3.82, -0.7, -0.87, 0.55, 4.20, -2.38, -4.57, 0.55, 0.87, 4.45, 3.46, -2.31, 3.86, -1.4, -2.45, 0.08, 0.92, 0.36, 1.29, 4.02, -5.57])
x2 = np.array ([0.58, -3.68, 2.39, -0.72, -0.83, 0.45, -1.20, -1.62, -4.50, -0.20, 2.31, 1.15, 1.60, -3.07, -1.20, 3.15, -3.34, 1.71, 1.48, 1.85, -0.02, 0.27, -0.41, -1.59, 1.77])
n = len(x1)
a = np.sum (x1)
y1 = np.sum (x2)

In [379]:
xy = np.sum (x1*x2) #X*Y скалярное произведение векторов
x  = 1/n*a #x1среднее
print("x:",x)

y = 1/n*y1 #x2среднее
print("y:",y)

x22 = np.sum (x1*x1) #скалярный квадрат
print("x^2:",x22)

x: 0.348
y: -0.14679999999999996
x^2: 185.5308


In [380]:
k = (xy - n*x*y)/(x22-x**2)
print("k:",k)

b = (y*xy**2 - xy*x*y)/x22-n*x**2
print("b:",b)

k: -0.565942570770409
b: -11.982246462215265


- Решение СЛАУ

In [381]:
M = np.random.randn(4, 4)
N = np.random.randn(4, 1)
print("M:",M, sep='\n')
print("N:",N, sep='\n')

M:
[[-0.44225873  0.76001074 -0.08231859 -0.63709108]
 [-0.74122198  0.07952953  0.89108471  0.67723084]
 [ 0.94839194  0.58876677 -0.82571953 -0.08342419]
 [ 0.7981097   0.35570113  0.24334527  1.81730062]]
N:
[[-1.26130811]
 [ 0.88470285]
 [ 0.15184798]
 [-0.82023998]]


Найдём ранг совместной матрицы

In [382]:
matrix = np.hstack ([M,N]) #совместная матрица
r = np.linalg.matrix_rank(matrix)
print ("Ранг совместной матрицы:", r, sep='\n')

Ранг совместной матрицы:
4


1) Решение СЛАУ

In [383]:
np.linalg.solve(M, N)

array([[ 85.57740823],
       [ 13.58099071],
       [113.43691281],
       [-55.88261419]])

2. Построим LU разложение

In [384]:
L, U, P = scipy.linalg.lu (M) #где P - матрица перестановки
print ("L:", L, sep='\n')
print ("U:", U, sep='\n')

L:
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
U:
[[ 1.          0.          0.          0.        ]
 [-0.46632485  1.          0.          0.        ]
 [ 0.84153995 -0.1350996   1.          0.        ]
 [-0.7815566   0.52165198  0.55942778  1.        ]]


2. Построим QR разложение

In [385]:
Q, R = linalg.qr(M)
print ("Q:", Q, sep='\n')
print ("R:", R, sep='\n')

Q:
[[-0.29280124  0.85993772  0.19629405  0.36911137]
 [-0.49073247  0.22833659 -0.57015134 -0.61803843]
 [ 0.62789115  0.40916351  0.2758518  -0.60186686]
 [ 0.52839548  0.20237278 -0.74853315  0.34574787]]
R:
[[ 1.51044006  0.2960725  -0.80306066  0.76207403]
 [ 0.          0.98460751 -0.15592946 -0.05958402]
 [ 0.          0.         -0.93414001 -1.89450374]
 [ 0.          0.          0.          0.02482583]]


3. Найти собственное значение 

In [389]:
evalue, evect = np.linalg.eig(M)
print ("Собственные значения:", evalue, sep='\n')
print ("Собственные векторы:", evect, sep='\n')

Собственные значения:
[ 1.87428412+0.j         -0.63328801+0.68500749j -0.63328801-0.68500749j
  0.02114382+0.j        ]
Собственные векторы:
[[-0.11900731+0.j          0.40447578+0.38355811j  0.40447578-0.38355811j
   0.55666964+0.j        ]
 [ 0.40057891+0.j         -0.44753582+0.12781815j -0.44753582-0.12781815j
   0.10994985+0.j        ]
 [ 0.01748333+0.j          0.66128397+0.j          0.66128397-0.j
   0.73618501+0.j        ]
 [ 0.90833261+0.j         -0.08564097-0.16740925j -0.08564097+0.16740925j
  -0.36886527+0.j        ]]


4*. Нормированные собственные векторы

a) найдем норму векторов

In [393]:
nv1 = np.linalg.norm (evect[:,0])
nv2 = np.linalg.norm (evect[:,1])
nv3 = np.linalg.norm (evect[:,2])
nv4 = np.linalg.norm (evect[:,3])

print ("Норма вектора 1:", nv1, sep='\n')
print ("Норма вектора 2:", nv2, sep='\n')
print ("Норма вектора 3:", nv3, sep='\n')
print ("Норма вектора 4:", nv4, sep='\n')

Норма вектора 1:
1.0
Норма вектора 2:
0.9999999999999999
Норма вектора 3:
0.9999999999999999
Норма вектора 4:
1.0


б) отнормируем собственные векторы

In [410]:
a = evect[:,0]
b = evect[:,1]
c = evect[:,2]
d = evect[:,3]

a1 = a/nv1
b1 = b/nv2
c1 = c/nv3
d1 = d/nv4

matrix1 = np.array ([a1, b1, c1, d1])
matrix1
matrix2 = np.transpose(matrix1)
matrix2

array([[-0.11900731+0.j        ,  0.40447578+0.38355811j,
         0.40447578-0.38355811j,  0.55666964+0.j        ],
       [ 0.40057891+0.j        , -0.44753582+0.12781815j,
        -0.44753582-0.12781815j,  0.10994985+0.j        ],
       [ 0.01748333+0.j        ,  0.66128397+0.j        ,
         0.66128397-0.j        ,  0.73618501+0.j        ],
       [ 0.90833261+0.j        , -0.08564097-0.16740925j,
        -0.08564097+0.16740925j, -0.36886527+0.j        ]])

In [412]:
A = np.array ([[1,3,5],[3,1,5],[5,5,1]])
A

array([[1, 3, 5],
       [3, 1, 5],
       [5, 5, 1]])

In [413]:
evalue, evect = np.linalg.eig(A)
print ("Собственные значения:", evalue, sep='\n')
print ("Собственные векторы:", evect, sep='\n')

Собственные значения:
[ 9.72841615 -2.         -4.72841615]
Собственные векторы:
[[-5.49434787e-01 -7.07106781e-01 -4.45108319e-01]
 [-5.49434787e-01  7.07106781e-01 -4.45108319e-01]
 [-6.29478221e-01  1.26858383e-17  7.77018127e-01]]


In [426]:
a = evect[:,0]
b = evect[:,1]
c = evect[:,2]

a1 = a/nv1
b1 = b/nv2
c1 = c/nv3

matrix1 = np.transpose (np.array ([a1, b1, c1]))
matrix1



array([[-5.49434787e-01, -7.07106781e-01, -4.45108319e-01],
       [-5.49434787e-01,  7.07106781e-01, -4.45108319e-01],
       [-6.29478221e-01,  1.26858383e-17,  7.77018127e-01]])