import numpy as np
import sympy

In [136]:
import numpy as np
import sympy as sp

In [138]:
x1 = np.array([1.93, -1.05, 0.7, -0.26, 1.44, 1.40, -0.64, 2.14, -2.07, -1.59, -3.42, -1.22, 2.06, 0.53, 1.15, -1.15, -0.23, -1.11, -0.59, 2.32, -3.58, 1.24, 1.82, 2.65, -3.67])
x2 = np.array([-0.85, -2.48, 2.33, -2.84, 0.41, -0.10, 3.38, -2.94, 1.68, 2.42, 1.37, -1.46, 1.64, -0.83, 2.92, 1.46, -2.82, 2.67, -2.43, 0.23, -1.17, -1.38, -3.92, 0.51, -0.12])
x3 = np.array([0.45, 0.37, 1.08, -1.68, 0.71, 0.61, 0.75, 0.49, -0.35, 0.44, -1.97, 1.13, 1.31, 0.45, 0.28, -0.01, -1.79, 0.58, -4.69, 2.75,-3.29, -1.98, 3.54, -0.74, 1.55])
n = len(x1)
Matrix = sp.Matrix([x1,x2,x3])
Matrix 

Matrix([
[ 1.93, -1.05,  0.7, -0.26, 1.44,  1.4, -0.64,  2.14, -2.07, -1.59, -3.42, -1.22, 2.06,  0.53, 1.15, -1.15, -0.23, -1.11, -0.59, 2.32, -3.58,  1.24,  1.82,  2.65, -3.67],
[-0.85, -2.48, 2.33, -2.84, 0.41, -0.1,  3.38, -2.94,  1.68,  2.42,  1.37, -1.46, 1.64, -0.83, 2.92,  1.46, -2.82,  2.67, -2.43, 0.23, -1.17, -1.38, -3.92,  0.51, -0.12],
[ 0.45,  0.37, 1.08, -1.68, 0.71, 0.61,  0.75,  0.49, -0.35,  0.44, -1.97,  1.13, 1.31,  0.45, 0.28, -0.01, -1.79,  0.58, -4.69, 2.75, -3.29, -1.98,  3.54, -0.74,  1.55]])

Составим матрицу ковариации

In [111]:
x1x1 = sum(x1*x1)/n
x1x2 = sum(x1*x2)/n
x1x3 = sum(x1*x3)/n
x2x1 = sum(x2*x1)/n
x2x2 = sum(x2*x2)/n
x2x3 = sum(x2*x3)/n
x3x1 = sum(x3*x1)/n
x3x2 = sum(x3*x2)/n
x3x3 = sum(x3*x3)/n
# перемножили векторы и отнормировали 
x3x1


1.192136

Далее из полученных значений составляем матрицу ковариации

In [112]:
matrix = np.array ([[x1x1, x1x2, x1x3],[x2x1, x2x2, x2x3], [x3x1, x3x2, x3x3]])
matrix 

array([[ 3.469936, -0.53986 ,  1.192136],
       [-0.53986 ,  4.291624,  0.671404],
       [ 1.192136,  0.671404,  3.072132]])

Найдем собственные числа

In [113]:
evalue, evect = np.linalg.eig(matrix)

print ("Собственные числа равны:", evalue, sep='\n')
print ("Собственные вектора равны:", evect, sep='\n')

Собственные числа равны:
[1.76842639 4.47572925 4.58953636]
Собственные вектора равны:
[[-0.60965357 -0.79016855 -0.06289822]
 [-0.32305194  0.17521987  0.93001905]
 [ 0.72385079 -0.58730883  0.3620889 ]]


In [114]:
m = evect
m

array([[-0.60965357, -0.79016855, -0.06289822],
       [-0.32305194,  0.17521987,  0.93001905],
       [ 0.72385079, -0.58730883,  0.3620889 ]])

Далее выполняем сортировку векторов по собственным числам от большего к меньшему и переставляем собственные вектора в порядке убывания собственных значений и составляем матрицу перехода

In [117]:
m1 = evect [:,0] #срез по столбцам
m2 = evect [:,1]
m3 = evect [:,2]

T = np.column_stack([m3,m2,m1])
T

m1:
[-0.60965357 -0.32305194  0.72385079]
m2:
[-0.79016855  0.17521987 -0.58730883]
m3:
[-0.06289822  0.93001905  0.3620889 ]


array([[-0.06289822, -0.79016855, -0.60965357],
       [ 0.93001905,  0.17521987, -0.32305194],
       [ 0.3620889 , -0.58730883,  0.72385079]])

Находим обратную матрицу перехода

In [118]:
T1 = np.linalg.inv (T)
T1

array([[-0.06289822,  0.93001905,  0.3620889 ],
       [-0.79016855,  0.17521987, -0.58730883],
       [-0.60965357, -0.32305194,  0.72385079]])

Вычисляем координаты всех выборочных точек в пространстве Y1,Y2,Y3

In [140]:
Y = T1*Matrix 
Y

Matrix([
[-0.748969752530077, -2.10643122801401,   2.51397165689197,  -3.23320993287424,  0.547817497385415,  0.039814818510182,   3.45528593905516,    -2.69143464437249,  1.56590020804404,  2.50997339608159, 0.775922874064865, -0.871931529427167,   1.86999737926127, -0.642311864182225,   2.74470757690304,  1.42653988153437,  -3.25632627777409, 2.76297946060492, -3.92103330805905,  1.06372499776314, -2.05421915943328,    -2.0783561149894, -2.47835473089871, 0.039683647074686, 0.680471979520777],
[ -1.93825116243439,  0.17782744219666, -0.779149230322905,  0.694498232831203,  -1.48299183571845,  -1.48201634293898,  0.657469401141119,    -2.49388843284044,  2.13557636616881,  1.42198418897026,  4.09942605264977,  0.044525650542797,   -2.1097611979342, -0.828510794034019, -0.561498294201078,  1.17038792718895,  0.738901544745084, 1.00428501535994,   2.7948935728157, -3.40798974591447,  4.55604221229846, -0.0587409393200502, -4.20404189203618, -1.56997599458616,  1.96856351358302],
[-0.576